<?php
/**
 * Created by PhpStorm.
 * User: yann
 * Date: 04/02/19
 * Time: 14:41
 */

namespace Composer\IO\Yaml;


use Symfony\Component\Yaml\Parser;

class YamlParser extends Parser
{
    public function parse($value, $exceptionOnInvalidType = false, $objectSupport = false, $objectForMap = false)
    {
        return parent::parse($value, $exceptionOnInvalidType, $objectSupport, $objectForMap); // TODO: Change the autogenerated stub
    }
}